AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-lambda-uk-news-scraper
Transform:
- AWS::Serverless-2016-10-31
Resources:

  GuardianScraper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/guardianScraper
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 300
      Description: Lambda that scrapes latest headlines from Guardian
      Layers:
        - !Ref ScraperLayer
      Policies:
        - AWSLambdaBasicExecutionRole

  ScraperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: scraper-dependencies
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
