AWSTemplateFormatVersion: 2010-09-09
Description: aws-lambda-uk-news-scraper
Transform: Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs14.x
    Environment:
      Variables:
        AwsRegion: eu-west-1

Resources:

  GuardianScraper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/guardianScraper.handler
      MemorySize: 512
      Timeout: 300
      Description: Lambda that scrapes latest headlines from Guardian
      Layers:
        - !Ref ScraperLayer
      Policies:
        - DynamoDBCrudPolicy:
          TableName: NewsScraperTable
      Environment:
        Variables:
          GuardianUrl: https://www.theguardian.com/uk


  ScraperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: scraper-dependencies
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain

  NewsScraperTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'newspaper'
          AttributeType: 'S'
        -
          AttributeName: 'date'
          AttributeType: 'S'
        -
          AttributeName: 'section'
          AttributeType: 'S'
        - 
          AttributeName: 'headline'
          AttributeType: 'S'
        -
          AttributeName: 'tag'
          AttributeType: 'S'
        -
          AttributeName: 'author'
          AttributeType: 'S'
        -
          AttributeName: 'contentType'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'PrimaryKey'
          KeyType: 'HASH'
        -
          AttributeName: 'SortKey'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: 'NewsScraperTable'



